### PR TITLE
Add community guide

### PR DESCRIPTION
**Pull request by juanis2112**
Co-authored-by: Sanket Verma <svsanketverma5@gmail.com>
Co-authored-by: Inessa Pawson <inessapawson@gmail.com>

### CODE REVIEW

**Review by InessaPawson — APPROVED** [review]
This is a great first draft. Thank you, @juanis2112 and @MSanKeys963!

**Comment by MSanKeys963** [comment]
I think this PR needs some fixing. The CI is failing, and I can't see the content over at https://learn.scientific-python.org/community/.

I tried fixing pre-commit errors in #59, but some tests are failing. Any ideas? 

CC: @juanis2112 @jarrodmillman @stefanv

**Comment by stefanv** [comment]
> I think it just need rebasing

[Here's a list](https://github.com/scientific-python/learn.scientific-python.org/pull/59/files) of the changes @jarrodmillman had to make to get it to pass.

**Comment by juanis2112** [comment]
Sorry @jarrodmillman. I’m pretty sure I ran the pre-commit and wasn’t expecting it to have so many errors.
Also @stefanv we were working with jarrod during the summit and he was helping me fix the PR but we never got to fixing it. After a while of looking at the errors Jarrod suggested that it was probably due to my PR being behind the main branch after the scikit hep guide changes were merged. Hence I thought that’s what was wrong with the PR.

**Comment by stefanv** [comment]
Hehe, yeap, I caused a bit of trouble there, but all good---it's sorted :)

**Pull request merged**
