### PR TITLE
ci: use dependabot for submodule

### PR DESCRIPTION
**Pull request by henryiii**
This doesn't do tags, AFAIK, but I think that's fine - tags are more for releasing sp-repo-review on PyPI. Dependabot also supports manually triggering, IIRC.

### CODE REVIEW

**Comment by henryiii** [comment]
One small downside, I don't seem to have permission to trigger a manual dependabot run, while the current method I can trigger. The plus side is that the dependabot PR will automatically run CI with the close and reopen step (or setting up a bot).

**Review by jarrodmillman — APPROVED** [review]

**Comment by jarrodmillman** [comment]
We are working on a system to better control the permissions. We should revisit your permissions then to make sure you have the access you need. If that takes more than a week, I will look into giving you access manually.

**Comment by jarrodmillman** [comment]
@henryiii I updated your permissions for this repo. Would you let me know if you are now able to trigger a manual dependabot run?

**Comment by henryiii** [comment]
Yes, I have the button. (Had to hunt a bit, as I forget where it was).

**Pull request merged**
